services:
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - mqvolumn:/var/lib/rabbitmq/
      - mqvolumn:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      - RABBITMQ_DEFAULT_USER=nxwbtk
      - RABBITMQ_DEFAULT_PASS=password

networks:
  rabbitmq_go_net:
volumes:
  mqvolumn:
